### ISSUE TITLE
Update executor path in Helm installation output

### ISSUE THREAD

**Issue by kate-goldenring** [spinkube/spin-operator#158]
I installed the shim with:
```sh
helm install spin-operator \
  --namespace spin-operator \
  --create-namespace \
  --devel \
  --wait \
  oci://ghcr.io/spinkube/spin-operator
```

The output recommends follow up steps of installing the runtime class and spin app executor; however the provided executor endpoint (https://github.com/spinkube/spin-operator/releases/download/v0.0.1/spin-operator.executor.yaml) does not exist. For now, we should add the executor that exists here https://github.com/spinkube/spin-operator/releases/download/v0.0.1/spin-operator.shim-executor.yaml to the [release](https://github.com/spinkube/spin-operator/releases/tag/v0.0.1) with name `spin-operator.executor.yaml`.
```sh
Pulled: ghcr.io/spinkube/spin-operator:0.0.1
Digest: sha256:33ff8ade7e1e37a54d23580a906404e4633a8cc57eb4b55182e1a390f8a30266
NAME: spin-operator
LAST DEPLOYED: Fri Mar  8 14:32:37 2024
NAMESPACE: spin-operator
STATUS: deployed
REVISION: 1
NOTES:
spin-operator 0.0.1 is now deployed!

Your release is named spin-operator.

To learn more about the release, try:

  $ helm --namespace spin-operator status spin-operator
  $ helm --namespace spin-operator get all spin-operator

Note: spin-operator requires a few additional resources to be present on the
Kubernetes cluster before it can run the first Spin application.

1. Install the containerd-shim-spin SpinAppExecutor:

  $ kubectl apply -f https://github.com/spinkube/spin-operator/releases/download/v0.0.1/spin-operator.executor.yaml

2. Install the wasmtime-spin-v2 RuntimeClass:

  $ kubectl apply -f https://github.com/spinkube/spin-operator/releases/download/v0.0.1/spin-operator.runtime-class.yaml

3. Finally, install the containerd wasm shim on at least one node. This shim is
necessary for running Spin application workloads. We use the Kwasm Operator
to handle this installation, via node annotations.

  $ kubectl annotate node <node> kwasm.sh/kwasm-node=true

You are now ready to deploy your first Spin app!

For further details, see this chart's README:

  $ helm show readme oci://ghcr.io/spinkube/spin-operator
```

**Comment by vdice** [comment]
@kate-goldenring I believe this can be closed now.  We've standardized on `spin-operator.shim-executor.yaml` now in [code/CI ](https://github.com/spinkube/spin-operator/blob/a650e4a06ee67389dc81ed0064cd9ac3addf60ba/Makefile#L167)and the chart [README](https://github.com/spinkube/spin-operator/blob/a650e4a06ee67389dc81ed0064cd9ac3addf60ba/charts/spin-operator/README.md?plain=1#L43)/[NOTES](https://github.com/spinkube/spin-operator/blob/a650e4a06ee67389dc81ed0064cd9ac3addf60ba/charts/spin-operator/templates/NOTES.txt#L16) files.
