### ISSUE TITLE
unable to hit external API from SPIN Go component running in SpinKube

### ISSUE THREAD

**Issue by camba1** [spinkube/spin-operator#216]
### What were you doing
Trying to run a simple SPIN Go component  in Kubernetes that hits an external (third party) API .

### What did you expect 
Component to hit the cat facts public API (https://catfact.ninja/fact) and return a fact that would then be sent to the end user

### What happened 
The component seems to thrown a " Runtime error" on the following line. Not additional logs printed. 

```go
req, err := spinhttp.Get("https://catfact.ninja/fact")
```

### Additional Info 

- Component runs fine locally outside of k3d
- Able to run other components in K8s that do not try to hit an external API
- Able to run another container (non-wasm) in the cluster and get the appropriate response from the cat fact api

### Steps to reproduce 

Create a simple http-go sample application
```shell
spin new -t http-go --accept-defaults simple-get-go  
```
change the contents of the init function in the main.go file to :
```go
func init() {
	spinhttp.Handle(func(w http.ResponseWriter, r *http.Request) {

		req, err := spinhttp.Get("https://catfact.ninja/fact")
		if err != nil {
			fmt.Printf("Problem getting cat fact. %s\n", err.Error())
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		decoder := json.NewDecoder(req.Body)
		newFact := struct {
			Fact   string `json:"fact"`
			Length int    `json:"length"`
		}{}

		err = decoder.Decode(&newFact)
		if err != nil {
			log.Println(err)
			return
		}

		w.Header().Set("Content-Type", "text/plain")
		fmt.Fprintln(w, newFact.Fact)
	})
}
```

Push container to the image repository
```shell
spin registry push --build bolbeck/simple-get-go    
```
Scaffold the K8s manifest
``` shell
mkdir k8s
spin kube scaffold --from bolbeck/simple-get-go --out k8s/simplegetgo.yaml
```
Deploy the container to k3d and port forward to it:
```shell
 kubectl apply -f k8s/simplegetgo.yaml       
kubectl port-forward svc/simple-get-go 8083:80     
```

Navigate to localhost:8083 in the browser (or curl it) and the application throws a "Runtime error" message

### Environment

k3d version v5.6.0
k3s version v1.27.5-k3s1 (default)
spin-operator 0.1.0

What is the best way to debug this in K3d given that the WASM container does not have a distro and thus I assume one cannot log into the container?

**Comment by endocrimes** [comment]
fixed in #207 and released in `v0.2.0` 🎉
