### ISSUE TITLE
Change domain from `spinoperator.dev` to `spinkube.dev`

### ISSUE THREAD

**Issue by calebschoepp** [spinkube/spin-operator#259]
Currently the domain for `SpinApp` and `SpinAppExecutor` CRs is `spinoperator.dev`. I thought it might make more sense to have it be `spinkube.dev`. Thoughts?

**Comment by endocrimes** [comment]
that's a full uninstall-reinstall upgrade process - which is subpar, but now might be the last time we can do that?

**Comment by calebschoepp** [comment]
> that's a full uninstall-reinstall upgrade process - which is subpar, but now might be the last time we can do that?

That's kind of my reasoning. If we want to do something like this, better now than later. We could also do it when we bump to `v1alpha2` or `v1beta1` too b/c I think that would require a reinstall too.

**Comment by endocrimes** [comment]
Upgrading versions we can do transparently - kubernetes will just return the old data through the new version.

**Comment by calebschoepp** [comment]
Let's just bring this up at the next spinkube meeting. If there's no interest in doing this than we can just close the issue.

**Comment by calebschoepp** [comment]
Outcome here is that I will write a SKIP about doing this.

**Comment by endocrimes** [comment]
In case it changes your desire to do this, we do own spinoperator.dev iirc

**Comment by calebschoepp** [comment]
Yep I'm aware, personally I still prefer the switch to spinkube.dev

**Comment by calebschoepp** [comment]
This is done now
