### ISSUE TITLE
Release v0.4.0

### ISSUE THREAD

**Issue by calebschoepp** [spinkube/spin-operator#336]
## Pre-requisites
- [x] https://github.com/spinkube/spin-plugin-kube/pull/89
- [x] https://github.com/spinkube/documentation/pull/240

## Afterwards
- [x] Write a small blog post.

**Comment by macolso** [comment]
Love the idea of cutting a blog post, @calebschoepp. Would this be scoped to Spin Operator v0.4, or if other projects have releases in the next week do you envision this content being broadened to "Updates in SpinKube"

**Comment by calebschoepp** [comment]
I originally envisioned this as scoped to Spin Operator, but I think broadening the scope seems reasonable.

**Comment by macolso** [comment]
@calebschoepp  if you're up for it, I think the reader would benefit from an e2e update on what's new holistically with the project. I've created an issue to track this work https://github.com/spinkube/documentation/issues/254

**Comment by goshlanguage** [comment]
hey team, I was trying to try spin kube following the [quickstart](https://www.spinkube.dev/docs/install/quickstart/) and I realized I couldn't install the spin operator

```sh
helm install spin-operator \
 --namespace spin-operator --create-namespace --version 0.4.0 --wait oci://ghcr.io/spinkube/charts/spin-operator 
Error: INSTALLATION FAILED: failed to download "oci://ghcr.io/spinkube/charts/spin-operator" at version "0.4.0"
```

I looked at the release job, and I see that it skipped the `publish chart` step

Am I missing something or is this an issue?

**Comment by calebschoepp** [comment]
Thanks for reaching out @goshlanguage.

I was unable to repro this issue.
- I followed the quickstart steps and was able to successfully install the Spin Operator.
- It looks like the chart is published [here](https://github.com/spinkube/spin-operator/pkgs/container/charts%2Fspin-operator/300881355?tag=0.4.0).
- I think this is the run that published it https://github.com/spinkube/spin-operator/actions/runs/11692458263.

All that being said, it could still be an issue that just doesn't arise on my particular system.

- Are there any more error messages you can share?
- Would you mind trying the quickstart again from a clean state (delete the cluster, etc.)?

**Comment by bacongobbler** [comment]
I can also confirm that I was able to follow the quickstart guide shortly after releasing spin-operator v0.4.0 without any issues.

Can you try fetching the chart from the OCI registry?

```sh
><> helm fetch oci://ghcr.io/spinkube/charts/spin-operator
Pulled: ghcr.io/spinkube/charts/spin-operator:0.4.0
Digest: sha256:1bf8fbd7dd6ce337c84a4eaac96886d6fa0bc5a0b8cfe3afaefa2a8fcd6371ae
```

**Comment by rajatjindal** [comment]
I think one of the scenario where we saw this happening in past is if the token for `ghcr.io` has expired on the system? (If I remember correctly it works if no token is set or the token is still valid, but fails if the token has expired).

**Comment by bacongobbler** [comment]
That's worth trying. Try this:

```
docker logout ghcr.io
helm fetch oci://ghcr.io/spinkube/charts/spin-operator
```

**Comment by goshlanguage** [comment]
Thanks for all the suggestions. I must be doing something wrong. I tried reauthenticating with a new token with package read scope, but don't seem to be able to fetch it

```sh
helm fetch oci://ghcr.io/spinkube/charts/spin-operator
Error: GET "https://ghcr.io/v2/spinkube/charts/spin-operator/tags/list": GET "https://ghcr.io/token?scope=repository%3Aspinkube%2Fcharts%2Fspin-operator%3Apull&service=ghcr.io": unexpected status code 403: denied: denied
```

Should I be able to pull it unauthenticated?
```sh
docker logout ghcr.io

Removing login credentials for ghcr.io

helm fetch oci://ghcr.io/spinkube/charts/spin-operator
Error: GET "https://ghcr.io/v2/spinkube/charts/spin-operator/tags/list": GET "https://ghcr.io/token?scope=repository%3Aspinkube%2Fcharts%2Fspin-operator%3Apull&service=ghcr.io": unexpected status code 403: denied: denied
```

**Comment by calebschoepp** [comment]
Closing this b/c v0.4.0 is released and it seems peoples issues have been resolved.
