### ISSUE TITLE
Support an executor that runs Spin directly in a container

### ISSUE THREAD

**Issue by calebschoepp** [spinkube/spin-operator#9]
Currently we support `containerd-shim-spin` and `cyclotron` executors. We also want to support running Spin directly in a container which might be useful if you want to:
- Configure plugins or trigger plugins not part of the containerd shim
- Test a new version of Spin not supported by the containerd shim
- Run workload in clusters where you cannot configure the runtimeClass

**Comment by adamreese** [comment]
@calebschoepp can this be closed with https://github.com/spinkube/spin-operator/pull/278 ?
